on:
    push:
        branches:
            - master





jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: "Testing Github action"
            run: pwd 

          - name: "Before"
            run: ls  
            
          - uses: actions/checkout@v3
          
          - name: "After"
            run: ls 
            
          - name: "Login To Docker Hub"
            run: docker login --username saleh264 --password ${{ secrets.DOCKER_TOKEN }}



            
